name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Set IMAGE_TAG environment variable
      run: |
        echo "IMAGE_TAG=$(date +%S)" >> $GITHUB_ENV
    
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag praneethrepo/recipe:$IMAGE_TAG
    - uses: docker/login-action@v2
      with:
        username: praneethrepo
        password: 15Pr@neeth
    - name: Push the Docker image
      run: docker push praneethrepo/recipe:$IMAGE_TAG
