name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        IMAGE_TAG=$()
        docker build . --file Dockerfile --tag praneethrepo/recipe:$(date)
    - uses: docker/login-action@v2
      with:
        username: praneethrepo
        password: 15Pr@neeth
    - name: Push the Docker image
      run: docker push praneethrepo/recipe:$(date)
